### ISSUE TITLE
Make correct use of Namespaces

### ISSUE THREAD

**Issue by marbosjo** [RobotnikAutomation/robotnik_leds#1]
Make correct use of Namespaces, for parameters, topics, and services, according to the best practices guideline. https://github.com/leggedrobotics/ros_best_practices/wiki

These are just general guidelines, but when possible, prefer to use the following in each case:

    Subscribers - usually public node handles.
    Publishers - usually private node handles for most output/visualization, occasionally necessary to use public for globally-used data (i.e., /odom topic).
     Parameters - almost always private node handle.

Never use global names. This is because they do not resolve properly when you push nodes into namespaces, and does not allow you to run more than one of your node at a time properly. Or use multiple robots on the same master. Define published topics and parameters relative to the nodes namespace:

Good: odometry, grid_map, cam0/camera_info
Bad: /odometry, /grid_map, /helicopter/cam0/camera_info

**Comment by jmnavarrete** [comment]
Ok, I will resolve this problem.

**Comment by marbosjo** [comment]
Done
